AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: telegram-geo-quiz

Parameters:
  TelegramBotToken:
    Type: String

Globals:
  Function:
    Timeout: 3

Resources:
  TelegramGeoQuiz:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: telegram-geo-quiz/src/
      Handler: app.handler
      Runtime: nodejs10.x
      Environment:
        Variables:
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
      Events:
        TelegramGeoQuiz:
          Type: Api
          Properties:
            Path: /
            Method: post

Outputs:
  TelegramGeoQuizApi:
    Description: "API Gateway endpoint URL for Prod stage for Telegram Geo Quiz function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
