AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: telegram-geo-quiz-${!Ref Environment}

Parameters:
  TelegramBotToken:
    Type: String
  Environment:
    Type: String

Globals:
  Function:
    Timeout: 3

Resources:
  TelegramGeoQuiz:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: telegram-geo-quiz/
      Handler: src/app.handler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LocationTable
      Environment:
        Variables:
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          LOCATION_TABLE_NAME: !Ref LocationTable
      Events:
        TelegramGeoQuiz:
          Type: Api
          Properties:
            Path: /
            Method: post

  LocationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: location
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: location
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  TelegramGeoQuizApi:
    Description: "API Gateway endpoint URL for Prod stage for Telegram Geo Quiz function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  LocationTableName:
    Description: "Name of the DynamoDB database for the locations"
    Value: !Ref LocationTable
