AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: telegram-geo-quiz

Globals:
  Function:
    Timeout: 3

Resources:
  TelegramGeoQuiz:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: telegram-geo-quiz/
      Handler: app.handler
      Runtime: nodejs10.x
      Events:
        TelegramGeoQuiz:
          Type: Api
          Properties:
            Path: /
            Method: get

Outputs:
  TelegramGeoQuizApi:
    Description: "API Gateway endpoint URL for Prod stage for Telegram Geo Quiz function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
