name: CI

on: push

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 12
      - name: Cache root node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}
      - name: Cache bot node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('telegram-geo-quiz/yarn.lock') }}
      - name: Install dependencies
        run: make dependencies

  build:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - name: Build TS
        run: make build

  test:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - name: Run unit tests
        run: make test-ci
